<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="8.9.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.3.0" />
    <PackageReference Include="NSubstitute" Version="5.3.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Core/Application/UseCases/Companies/" />
    <Folder Include="Core/Application/UseCases/Companies/Commands/" />
    <Folder Include="Core/Application/UseCases/Companies/Commands/UpdateCompanyAddressInfo/" />
    <Folder Include="Core/Application/UseCases/Companies/Commands/UpdateCompanyBrandInfo/" />
    <Folder Include="Core\Application\UseCases\Amenities\" />
    <Folder Include="Core\Application\UseCases\Amenities\Commands\" />
    <Folder Include="Core\Application\UseCases\Amenities\Commands\CreateAmenity\" />
    <Folder Include="Core\Application\UseCases\Bookings\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\CancelBooking\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\ChangeAssignedRoom\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\ChangeBookingSource\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\CompleteBooking\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\ConfirmBooking\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\MarkAsNoShow\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\UpdateCancellationReason\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\UpdateCheckInOutTimes\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\UpdateGuestCount\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\UpdateSpecialRequests\" />
    <Folder Include="Core\Application\UseCases\Bookings\Commands\UpdateTotalPrice\" />
    <Folder Include="Core\Application\UseCases\Companies\Commands\UpdateCompanyContactInfo\" />
    <Folder Include="Core\Application\UseCases\Companies\Commands\UpdateCompanyRnc\" />
    <Folder Include="Core\Application\UseCases\Companies\Queries\" />
    <Folder Include="Core\Application\UseCases\Guests\" />
    <Folder Include="Core\Application\UseCases\Guests\Commands\" />
    <Folder Include="Core\Application\UseCases\Guests\Queries\" />
    <Folder Include="Core\Application\UseCases\Rooms\Commands\ChangeRoomType\" />
    <Folder Include="Core\Application\UseCases\Rooms\Commands\UpdateAvailabilityStatus\" />
    <Folder Include="Core\Application\UseCases\Rooms\Commands\UpdateHygieneStatus\" />
    <Folder Include="Core\Application\UseCases\RoomTypes\" />
    <Folder Include="Core\Application\UseCases\RoomTypes\Commands\" />
    <Folder Include="Core\Application\UseCases\RoomTypes\Queries\" />
    <Folder Include="Core\Application\UseCases\RoomTypes\Queries\GetAllRoomTypes\" />
    <Folder Include="Core\Application\UseCases\RoomTypes\Queries\GetRoomTypeById\" />
    <Folder Include="Core\Domain\Discounts\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrisaPMS.Application\BrisaPMS.Application.csproj" />
    <ProjectReference Include="..\BrisaPMS.Domain\BrisaPMS.Domain.csproj" />
  </ItemGroup>

</Project>