<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>29f87b1a-1f19-4a0c-b74b-a0d7341a5e94</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrisaPMS.Application\BrisaPMS.Application.csproj" />
    <ProjectReference Include="..\BrisaPMS.Identity\BrisaPMS.Identity.csproj" />
    <ProjectReference Include="..\BrisaPMS.Persistence\BrisaPMS.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DTOs\Users\" />
  </ItemGroup>

</Project>
